In [1]:
import pandas as pd

In [5]:
file_path = '../data/Cuernavaca_1dia_comas_Nans.csv'
df = pd.read_csv(file_path, index_col=0, parse_dates=True)
df.head()

                       To   Ws  Wd      P  Ig  Ib  Id observacion
tiempo
2012-01-01 00:00:00   NaN  0.0  26  87415   0   0   0          Sí
2012-01-01 01:00:00  18.6  0.0  26  87602   0   0   0          No
2012-01-01 02:00:00  17.9  0.0  30  87788   0   0   0          No
2012-01-01 03:00:00   NaN  0.0  30  87554   0   0   0          No
2012-01-01 04:00:00  16.6  0.0  27  87321   0   0   0          No